POST http://localhost:3001/addHut HTTP/1.1
Content-type: application/json

{
	"Hut": {
		"Name": "2185",
		"Elevation": 0.0,
		"City": "city",
		"Province": "province",
		"Region": "region",
		"Country": "country",
		"WhenOpen": "whenOpen",
		"Beds": 1,
		"AvgPrice": 0.0,
		"Description": "description",
		"Email": "email",
		"Phone": 1234,
		"Website": "website",
		"Coord": "coord"
	}
}