name: SonarCloud Coverage
on:
  push:
    branches: ["main"]

jobs:
  sonarcloud:
    name: create-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./server
        run: npm install jest
      - name: Test and coverage
        working-directory: ./server
        run: npm run cover
      - name: Upload Unit test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: unit-coverage-report
          path: ./server/coverage/lcov.info

    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: create-coverage
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}